// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEfu1HkwoJKTGEhm6lwTpp8bJa9MlHtYE',
    appId: '1:266075240568:web:673d7821891ad5d47ed58d',
    messagingSenderId: '266075240568',
    projectId: 'aplikasi-388e7',
    authDomain: 'aplikasi-388e7.firebaseapp.com',
    storageBucket: 'aplikasi-388e7.firebasestorage.app',
    measurementId: 'G-P7TLX9X0KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgyEzVCxBrfpjPrkYCu-VCXKpTjk3SaJw',
    appId: '1:266075240568:android:309a70c5cb2d4f947ed58d',
    messagingSenderId: '266075240568',
    projectId: 'aplikasi-388e7',
    storageBucket: 'aplikasi-388e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE-T_G9g__0K4vPocfGqn4ACxxSNmYTZ0',
    appId: '1:266075240568:ios:40a400c6a4e17d1c7ed58d',
    messagingSenderId: '266075240568',
    projectId: 'aplikasi-388e7',
    storageBucket: 'aplikasi-388e7.firebasestorage.app',
    iosBundleId: 'com.durzaam.dakservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE-T_G9g__0K4vPocfGqn4ACxxSNmYTZ0',
    appId: '1:266075240568:ios:9a7e9ba5036fb54c7ed58d',
    messagingSenderId: '266075240568',
    projectId: 'aplikasi-388e7',
    storageBucket: 'aplikasi-388e7.firebasestorage.app',
    iosBundleId: 'com.example.webviewFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEfu1HkwoJKTGEhm6lwTpp8bJa9MlHtYE',
    appId: '1:266075240568:web:d914df6f0e7344b97ed58d',
    messagingSenderId: '266075240568',
    projectId: 'aplikasi-388e7',
    authDomain: 'aplikasi-388e7.firebaseapp.com',
    storageBucket: 'aplikasi-388e7.firebasestorage.app',
    measurementId: 'G-Y8XM6DWJX8',
  );

}